protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout = 'main';

	// public $defaultAction =  'dummy';
	
	/**
	 * Declares class-based actions.
	 */
	/*public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}*/

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */

	public function actionIndex()
	{
		if (Config::value('dummy'))
			$this->redirect(array('dummy'));
		
		$services = Service::model()->findAll();

		$this->render('index', array(
			'services' => $services,
		));
	}

	public function actionDummy()
	{
		$this->render('dummy');
	}

	public function actionService()
	{
		$this->layout = 'info';
		
		$models = Service::model()->findAll();

		$this->render('services', array(
			'models' => $models,
			'feedback' => new FeedbackForm,
		));
	}

	public function actionGallery()
	{
		$this->layout = 'info';

		$models = Project::model()->with(array('media', 'media.items'))->findAll();

		$this->render('gallery', array(
			'models' => $models,
		));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		// $model=new ContactForm;

		// if (isset($_POST['ContactForm']))
		// {
		// 	$model->attributes=$_POST['ContactForm'];
		// 	$model->send();
		// }

		// $this->redirectBack('site/index');

		$this->layout = 'info';
		$this->render('contact');
	}

	public function actionFeedback()
	{
		if (!Yii::app()->request->isAjaxRequest)
			throw new CHttpException(400);
		
		$model = new FeedbackForm;
		
		if (isset($_POST['FeedbackForm']))
		{
			$model->attributes = $_POST['FeedbackForm'];

			$valid = $model->validate();

			if ($valid)
			{
				if ($model->send())
				{
					echo CJSON::encode(array(
						'status' => 'success',
					));
				}
				else
					throw new CHttpException(500);				
				
				Yii::app()->end();
			}

			echo CActiveForm::validate($model);
		}	
		else
			throw new CHttpException(400);
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form

		$this->layout = 'admin/login';
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/info.php
<!DOCTYPE html>
<html>

<head>
	<base href="<?= Yii::app()->getBaseUrl(true); ?>/"/>
	<meta charset="utf-8" />
	<title>ArtMetall - Услуги</title>
	<link rel="stylesheet" href="style.css" />
	<!--?php Yii::app()->clientScript->registerCoreScript('jquery'); ?-->

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	
	<link href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.css" rel="stylesheet"> <!-- 3 KB -->
	<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.5.1/fotorama.js"></script> <!-- 16 KB -->
</head>

<body>
	<div class="page-wrapper">
		<div class="b-header">
			<div class="b-header--content">
				<a href="<?= Yii::app()->createUrl('site/index'); ?>"><i class="s s--header_logo"></i></a>

				<div class="header--contacts">
					<span class="header__telephone"><a href="tel:<?= Config::value('phone', array('Config', 'parseTel')); ?>"><?= Config::value('phone'); ?></a></span>
					<a href="mailto:<?= Config::value('email'); ?>" class="header__mail"><?= Config::value('email'); ?></a>
				</div>
			</div>
		</div>

		<div class="menu">
			<?php $this->widget('zii.widgets.CMenu', array(
				'htmlOptions' => array(
					'class' => 'b-menu',
				),
				'items' => array(
					array('label' => 'Главная', 'url' => array('site/index')),
					array('label' => 'Услуги', 'url' => array('site/service')),
					array('label' => 'Портфолио', 'url' => array('site/gallery')),
					array('label' => 'Контакты', 'url' => array('site/contact')),
				),
			)); ?>
		</div>

		<div class="b-content">
			<?= $content; ?>
		</div>

		<div class="page-buffer"></div>
	</div>

	<div class="page-footer">
		<div class="b-footer">
			<div class="page__layout">
				<ul class="b-main--footer">
					<li><p class="b-main--footer_copyright">© <?= date('Y');?> ArtMetall</p></li>
					<li><p class="b-main--footer_address"><?= Config::value('address'); ?></p></li>
					<li><p class="b-main--footer_telephone"><?= Config::value('phone'); ?></p></li>
				</ul>
			</div>
		</div>
	</div>

	<div class="popup">
		<span class="popup__text">Спасибо за ваш вопрос! Скоро мы с вами свяжемся!</span>
	</div>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
(w[c] = w[c] || []).push(function() {
try {
w.yaCounter28139490 = new Ya.Metrika({id:28139490,
webvisor:true,
clickmap:true,
trackLinks:true,
accurateTrackBounce:true});
} catch(e) { }
});

var n = d.getElementsByTagName("script")[0],
s = d.createElement("script"),
f = function () { n.parentNode.insertBefore(s, n); };
s.type = "text/javascript";
s.async = true;
s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

if (w.opera == "[object Opera]") {
d.addEventListener("DOMContentLoaded", f, false);
} else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28139490" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body>

</html>

protected/views/layouts/mail.php
<html>
	<body>
		<?php echo $content; ?>
	</body>
</html>

protected/views/layouts/main.php
<!DOCTYPE html>
<html>

<head>
	<base href="<?= Yii::app()->request->baseUrl; ?>/"/>
	<meta charset="utf-8" />
	<title>ArtMetall</title>
	<link rel="stylesheet" href="style.css" />
</head>

<body>
		<div class="b-main">
			<?= $content; ?>
		</div>
</body>

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
(w[c] = w[c] || []).push(function() {
try {
w.yaCounter28139490 = new Ya.Metrika({id:28139490,
webvisor:true,
clickmap:true,
trackLinks:true,
accurateTrackBounce:true});
} catch(e) { }
});

var n = d.getElementsByTagName("script")[0],
s = d.createElement("script"),
f = function () { n.parentNode.insertBefore(s, n); };
s.type = "text/javascript";
s.async = true;
s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

if (w.opera == "[object Opera]") {
d.addEventListener("DOMContentLoaded", f, false);
} else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/28139490" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</html>