protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
	public $layout = 'main';

	// public $defaultAction =  'dummy';
	
	/**
	 * Declares class-based actions.
	 */
	/*public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}*/

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */

	public function actionIndex()
	{
		if (Config::value('dummy'))
			$this->redirect(array('dummy'));
		
		$services = Service::model()->findAll();

		$this->render('index', array(
			'services' => $services,
		));
	}

	public function actionDummy()
	{
		$this->render('dummy');
	}

	public function actionService()
	{
		$this->layout = 'info';
		
		$models = Service::model()->findAll();

		$this->render('services', array(
			'models' => $models,
			'feedback' => new FeedbackForm,
		));
	}

	public function actionGallery()
	{
		$this->layout = 'info';

		$models = Project::model()->with(array('media', 'media.items'))->findAll();

		$this->render('gallery', array(
			'models' => $models,
		));
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		// $model=new ContactForm;

		// if (isset($_POST['ContactForm']))
		// {
		// 	$model->attributes=$_POST['ContactForm'];
		// 	$model->send();
		// }

		// $this->redirectBack('site/index');

		$this->layout = 'info';
		$this->render('contact');
	}

	public function actionFeedback()
	{
		if (!Yii::app()->request->isAjaxRequest)
			throw new CHttpException(400);
		
		$model = new FeedbackForm;
		
		if (isset($_POST['FeedbackForm']))
		{
			$model->attributes = $_POST['FeedbackForm'];

			$valid = $model->validate();

			if ($valid)
			{
				if ($model->send())
				{
					echo CJSON::encode(array(
						'status' => 'success',
					));
				}
				else
					throw new CHttpException(500);				
				
				Yii::app()->end();
			}

			echo CActiveForm::validate($model);
		}	
		else
			throw new CHttpException(400);
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form

		$this->layout = 'admin/login';
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/site/_feedback.php
				<!-- must be modal window -->

				<?php $form = $this->beginWidget('CActiveForm', array(
					'id' => 'feedback-form-' . $i,
					'htmlOptions' => array(
						'class' => 'b-service--backform',
					),
					'enableClientValidation' => true,
					// 'enableAjaxValidation' => true,
					'clientOptions' => array(
						'validateOnSubmit' => true,
						'validateOnChange' => false,
						'validateOnInput' => false,
						// 'hideErrorMessage' => true,
					),
				)); ?>

					<div>
						<?= $form->textField($feedback, 'theme', array(
							'placeholder' => $feedback->getAttributeLabel('theme'),
						)); ?>
						<?= $form->error($feedback, 'theme');?>
					</div>

					<div>
						<?= $form->textField($feedback, 'email', array(
							'placeholder' => $feedback->getAttributeLabel('email'),
						)); ?>
						<?= $form->error($feedback, 'email');?>
					</div>

					<div>
						<?= $form->textField($feedback, 'phone', array(
							'placeholder' => $feedback->getAttributeLabel('phone'),
						)); ?>
						<?= $form->error($feedback, 'phone');?>
					</div>

					<div>
						<?= $form->textArea($feedback, 'body', array(
							'placeholder' => $feedback->getAttributeLabel('body'),
						)); ?>
						<?= $form->error($feedback, 'body');?>
					</div>

					<?= CHtml::ajaxSubmitButton('Отправить', $this->createUrl('site/feedback'), array(
						'type' => 'POST',
						'dataType' => 'json',
						'success' =>
<<<JS
function(data) {
	if(data.status=="success")
	{
		$(".popup").slideDown();
        $("#feedback-form-{$i}")[0].reset();
        $(".popup").delay(2000).slideUp();
	}
	else
	{
		$.each(data, function(key, val) 
		{
			$("#feedback-form-{$i} #"+key+"_em_").text(val);
			$("#feedback-form-{$i} #"+key+"_em_").show();
		});
	}
}
JS
						,
						'error' => 'function () {alert(\'nope\')}',
					), array(
							'class' => 'b-service--submit',
					)); ?>

				<?php $this->endWidget(); ?>
				
				<!-- must be modal window -->

protected/views/site/contact.php
<b>Наш адрес:</b>
<p><?= Config::value('address'); ?></p>

<b>Контактный телефон:</b>
<p><?= Config::value('phone'); ?></p>

<b>Контактный e-mail</b><br />
<a href="mailto:<?= Config::value('email'); ?>"><?= Config::value('email'); ?></a>

<div style="display: block; height: 30px;"></div>

<?php $this->renderPartial('_feedback', array(
	'i' => 0,
	'feedback' => new FeedbackForm,
)); ?>

<div style="display: block; height: 30px;"></div>

<a id="firmsonmap_biglink" href="http://maps.2gis.ru/#/?history=project/irkutsk/center/104.30507449451,52.277815150148/zoom/18/state/widget/id/1548640653103660/firms/1548640653103660">Перейти к большой карте</a>
<script charset="utf-8" type="text/javascript" src="http://firmsonmap.api.2gis.ru/js/DGWidgetLoader.js"></script>
<script charset="utf-8" type="text/javascript">new DGWidgetLoader({"borderColor":"#a3a3a3","width":"100%","height":"450","wid":"b1afc0e8daee8e8459ed939f37aec5a7","pos":{"lon":"104.30507449451","lat":"52.277815150148","zoom":"18"},"opt":{"ref":"hidden","card":["name","contacts","schedule","payings"],"city":"irkutsk"},"org":[{"id":"1548640653103660","hash":"ge4iqa34691IJ1HJf1g7uvgc43660J34be88578834068658723e69G41J0I99669f"}]});</script>
<noscript style="color:#c00;font-size:16px;font-weight:bold;">Виджет карты использует JavaScript. Включите его в настройках вашего браузера.</noscript>

protected/views/site/dummy.php
		<i class="s s--logo"></i>

	
			<style>
				.b-dummy {
				  	-webkit-font-smoothing: antialiased;
					top: 65%; /* Отступ в процентах от верхнего края окна */
					/*left: 50%;  Отступ в процентах от левого края окна */
					/*width: 600px;  Ширина блока */
					width: 100%;
					height: 600px; /* Высота блока */
					position: absolute; /* Абсолютное позиционирование блока */
					margin-top: -160px; /* Отрицательный отступ от верхнего края страницы, должен равняться половине высоты блока со знаком минус */
					/*margin-left: -200px;  Отрицательный отступ от левого края страницы, должен равняться половине высоты блока со знаком минус */
					text-align: center;
					color: #FFFFFF;
					z-index: 100;
				}
				.b-dummy p
				{
					font-size: 34px;
				}
				.b-dummy p a
				{
					color: #AAA;
					text-decoration: none;
					
				}
				.b-dummy p a:hover
				{
					color: #FFF;
				}
			</style>

			<div class="b-dummy">
				<p>
					Извините, сайт в разработке.
				</p>
				<p>&nbsp;</p>
				<p>
					Если у вас есть вопросы, звоните <a href="tel:89025775634">8 (902) 577-56-34</a>
				</p>
			</div>

protected/views/site/error.php
<?php
/* @var $this SiteController */
/* @var $error array */

$this->pageTitle=Yii::app()->name . ' - Error';
$this->breadcrumbs=array(
	'Error',
);
?>

<div class="b-error">
	<h2><?php echo $code; ?></h2>

	<div class="error">
	<?php echo CHtml::encode($message); ?>
	</div>

	<a href="<?= $this->createUrl('site/index'); ?>" class="b-error__link">Вернуться на главную страницу</a>
</div>

protected/views/site/gallery.php
	<?php foreach ($models as $model): ?>
		<ul class="b-service--items">
			<li>
				<div class="b-service--items_imagewrapper">
					<!-- <img src="images/service_1.jpg"> -->
					<?= CHtml::image($model->image->thumb('logo')); ?>
				</div>

				<h3>Заказчик: <?= $model->name; ?></h3>

				<?= $model->description; ?>

				<div style="clear: both;"></div>

				<div class="b-service--items__content" style="display: none;">
					<?= $model->content; ?>
				</div>

				<div class="fotorama fotorama_big" data-width="100%" data-height="400" data-fit="cover" data-nav="thumbs" data-allowfullscreen="true">
				<?php foreach ($model->media->items as $item): ?>
					<?= CHtml::image($item->content); ?>
				<?php endforeach; ?>
				</div>

				<button class="b-service--items_button">Открыть подробное описание</button>
			</li>
		</ul>
	<?php endforeach; ?>

<script type="text/javascript">
	$( ".b-service--items li .b-service--items_button" ).click(function() {
		if ($(this).parent('li').find('.fotorama_big').hasClass("active_slider")) {
			$(this).parent('li').find('.b-service--items_button').text('Открыть подробное описание');
			$(this).parent('li').find('.b-service--items__content').slideUp();
			$(this).parent('li').find('.fotorama_big').slideUp();
			$(this).parent('li').find('ul').slideUp();
			$(this).parent('li').find('.fotorama_big').removeClass("active_slider");
		} else {
			$(this).parent('li').find('.b-service--items_button').text('Закрыть подробное описание');
			$(this).parent('li').find('ul').slideDown();
			$(this).parent('li').find('.fotorama_big').slideDown();
			$(this).parent('li').find('.b-service--items__content').slideDown();
			$(this).parent('li').find('.fotorama_big').addClass("active_slider");
		};
 	});
 </script>

protected/views/site/index.php
		<i class="s s--logo"></i>

		<span class="b-main--text">
			<?php foreach ($services as $service): ?>
				<!-- Металлокострукции<br />Металлоизделия<br />Плазменная резка<br />Портальные станки с ЧПУ<br />Водосливные системы и доборные элементы -->
				<a href="<?= $this->createUrl('service'); ?>#service_<?= $service->alias; ?>"><?= $service->name; ?></a><br />
			<?php endforeach; ?>
		</span>

		<div class="b-main--links-block">
			<a href="<?= Yii::app()->createUrl('site/service'); ?>" class="b-main--links">услуги</a>
			<a href="<?= Yii::app()->createUrl('site/gallery'); ?>" class="b-main--links">галерея</a>
			<a href="<?= Yii::app()->createUrl('site/contact'); ?>" class="b-main--links">контакты</a>
		</div>

		<ul class="b-main--footer">
			<li><p class="b-main--footer_copyright">© <?= date('Y');?> ArtMetall</p></li>
			<li><p class="b-main--footer_address"><?= Config::value('address'); ?></p></li>
			<li><p class="b-main--footer_telephone"><?= Config::value('phone'); ?></p></li>
		</ul>

protected/views/site/login.php
<div class="container">

	<?php if (Yii::app()->user->hasFlash('password')): ?>
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert">×</button>
			<?= Yii::app()->user->getFlash('password'); ?>
		</div>
	<?php endif; ?>
	
	<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
		'hideInlineErrors' => true,
		'htmlOptions' => array(
			'class' => 'form-signin',
		),
	)); ?>
	<h2 class="form-signin-heading">Вход</h2>
	<?= $form->errorSummary($model, 'Возникли следующие ошибки:') ?>
	<?=
	$form->textFieldControlGroup($model, 'username', array(
		'class' => 'input-block-level',
		'label' => false,
		'placeholder' => $model->getAttributeLabel('username')
	))?>
	<?=
	$form->passwordFieldControlGroup($model, 'password', array(
		'class' => 'input-block-level',
		'label' => false,
		'placeholder' => $model->getAttributeLabel('password')
	))?>

	<button class="btn btn-large btn-primary" type="submit">Войти</button>
	<!--
	<a href="<?= $this->createUrl('admin/site/passwordRecovery'); ?>" class="btn btn-large" type="submit">Я забыл пароль</a>
	-->
	<?php $this->endWidget(); ?>

</div> <!-- /container -->

protected/views/site/services.php
		<ul class="b-service--anchor">
			<?php foreach ($models as $model): ?>
			<li>
				<a href="<?= Yii::app()->request->url; ?>#service_<?= $model->alias; ?>">
					<div class="b-service--anchor_imagewrapper">
						<?= CHtml::image($model->image->thumb('menu')); ?>
					</div>
					<p><?= $model->name; ?></p>
				</a>
			</li>
			<?php endforeach; ?>
		</ul>
		<ul class="b-service--items">
			<?php $i = 0; ?>
			<?php foreach ($models as $model): ?>

			<li>
				<h2 id="service_<?= $model->alias; ?>"><?= $model->name; ?></h2>

				<?php if ($model->media !== null): ?>
				<div class="b-service--items_imagewrapper">
					<div class="fotorama" data-width="100%" data-height="250px" data-fit="cover" style="border-radius: 5px;">
						<?php foreach ($model->media->items as $image): ?>
							<?= CHtml::image($image->content); ?>
						<?php endforeach; ?>
					</div>
				</div>
				<?php endif; ?>

				<div class="b-service--content">
					<?= $model->description; ?>
				</div>

				<div style="clear: both;"></div>

				<div class="b-service--detailed">
					<?= $model->content; ?>
					<?php foreach ($model->albums as $album): ?>
						<div class="b-service--fotorama">
							<div class="fotorama" data-width="100%" data-height="250px" data-fit="cover" data-allowfullscreen="true">
								<?php foreach ($album->items as $image): ?>
									<?= CHtml::image($image->content); ?>
								<?php endforeach; ?>
							</div>
						</div>
					<?php endforeach; ?>
				</div>

				<div style="clear: both;"></div>

				<button class="b-service--items_button service">Открыть подробное описание</button>

				<div style="clear: both;"></div>
			</li>
			<?php endforeach; ?>
		</ul>

		<script type="text/javascript">
		 	$('.b-service--items').on('click', '.service', function(evt) {
		 		if ($(this).parent('li').find('.b-service--detailed').hasClass("active_slider")) {

					$(this).parent('li').find('.b-service--items_button').text('Открыть подробное описание');
					$(this).parent('li').find('.b-service--detailed').slideUp();
					$(this).parent('li').find('.b-service--fotorama').slideUp();
					$(this).parent('li').find('ul').slideUp();
					$(this).parent('li').find('.b-service--detailed').removeClass("active_slider");

				} else {

					$(this).parent('li').find('.b-service--items_button').text('Закрыть подробное описание');
					$(this).parent('li').find('ul').slideDown();
					$(this).parent('li').find('.b-service--fotorama').slideDown();
					$(this).parent('li').find('.b-service--detailed').slideDown();
					$(this).parent('li').find('.b-service--detailed').addClass("active_slider");

				};
		 	});
		 </script>